#ifndef _COLOR_H_
#define _COLOR_H_

typedef struct Color {
  double r;
  double g;
  double b;
  double a;
} bl_color;

bl_color* bl_color_rgba(double r, double g, double b, double a);
bl_color* bl_color_rgb(double r, double g, double b);
bl_color* bl_color_rgba_int(int r, int g, int b, int a);
bl_color* bl_color_rgb_int(int r, int g, int b);
bl_color* bl_color_int_24(int value);
bl_color* bl_color_int_32(int value);
bl_color* bl_color_lerp(bl_color *color_a, bl_color *color_b, double t);
bl_color* bl_color_random_rgb();
bl_color* bl_color_hsv(double h, double s, double v);
bl_color* bl_color_grey(double shade);
bl_color* bl_color_grey_int(int shade);
bl_color* bl_color_random_grey();
bl_color* bl_color_random_grey_range(double min, double max);

bl_color* bl_color_blueviolet();
bl_color* bl_color_brown();
bl_color* bl_color_aliceblue();
bl_color* bl_color_antiquewhite();
bl_color* bl_color_aqua();
bl_color* bl_color_aquamarine();
bl_color* bl_color_azure();
bl_color* bl_color_beige();
bl_color* bl_color_bisque();
bl_color* bl_color_black();
bl_color* bl_color_blanchedalmond();
bl_color* bl_color_blue();
bl_color* bl_color_burlywood();
bl_color* bl_color_cadetblue();
bl_color* bl_color_chartreuse();
bl_color* bl_color_chocolate();
bl_color* bl_color_coral();
bl_color* bl_color_cornflowerblue();
bl_color* bl_color_cornsilk();
bl_color* bl_color_crimson();
bl_color* bl_color_cyan();
bl_color* bl_color_darkblue();
bl_color* bl_color_darkcyan();
bl_color* bl_color_darkgoldenrod();
bl_color* bl_color_darkgray();
bl_color* bl_color_darkgreen();
bl_color* bl_color_darkgrey();
bl_color* bl_color_darkkhaki();
bl_color* bl_color_darkmagenta();
bl_color* bl_color_darkolivegreen();
bl_color* bl_color_darkorange();
bl_color* bl_color_darkorchid();
bl_color* bl_color_darkred();
bl_color* bl_color_darksalmon();
bl_color* bl_color_darkseagreen();
bl_color* bl_color_darkslateblue();
bl_color* bl_color_darkslategray();
bl_color* bl_color_darkslategrey();
bl_color* bl_color_darkturquoise();
bl_color* bl_color_darkviolet();
bl_color* bl_color_deeppink();
bl_color* bl_color_deepskyblue();
bl_color* bl_color_dimgray();
bl_color* bl_color_dimgrey();
bl_color* bl_color_dodgerblue();
bl_color* bl_color_firebrick();
bl_color* bl_color_floralwhite();
bl_color* bl_color_forestgreen();
bl_color* bl_color_fuchsia();
bl_color* bl_color_gainsboro();
bl_color* bl_color_ghostwhite();
bl_color* bl_color_gold();
bl_color* bl_color_goldenrod();
bl_color* bl_color_gray();
bl_color* bl_color_green();
bl_color* bl_color_greenyellow();
bl_color* bl_color_honeydew();
bl_color* bl_color_hotpink();
bl_color* bl_color_indianred();
bl_color* bl_color_indigo();
bl_color* bl_color_ivory();
bl_color* bl_color_khaki();
bl_color* bl_color_lavender();
bl_color* bl_color_lavenderblush();
bl_color* bl_color_lawngreen();
bl_color* bl_color_lemonchiffon();
bl_color* bl_color_lightblue();
bl_color* bl_color_lightcoral();
bl_color* bl_color_lightcyan();
bl_color* bl_color_lightgoldenrodyellow();
bl_color* bl_color_lightgray();
bl_color* bl_color_lightgreen();
bl_color* bl_color_lightgrey();
bl_color* bl_color_lightpink();
bl_color* bl_color_lightsalmon();
bl_color* bl_color_lightseagreen();
bl_color* bl_color_lightskyblue();
bl_color* bl_color_lightslategray();
bl_color* bl_color_lightslategrey();
bl_color* bl_color_lightsteelblue();
bl_color* bl_color_lightyellow();
bl_color* bl_color_lime();
bl_color* bl_color_limegreen();
bl_color* bl_color_linen();
bl_color* bl_color_magenta();
bl_color* bl_color_maroon();
bl_color* bl_color_mediumaquamarine();
bl_color* bl_color_mediumblue();
bl_color* bl_color_mediumorchid();
bl_color* bl_color_mediumpurple();
bl_color* bl_color_mediumseagreen();
bl_color* bl_color_mediumslateblue();
bl_color* bl_color_mediumspringgreen();
bl_color* bl_color_mediumturquoise();
bl_color* bl_color_mediumvioletred();
bl_color* bl_color_midnightblue();
bl_color* bl_color_mintcream();
bl_color* bl_color_mistyrose();
bl_color* bl_color_moccasin();
bl_color* bl_color_navajowhite();
bl_color* bl_color_navy();
bl_color* bl_color_oldlace();
bl_color* bl_color_olive();
bl_color* bl_color_olivedrab();
bl_color* bl_color_orange();
bl_color* bl_color_orangered();
bl_color* bl_color_orchid();
bl_color* bl_color_palegoldenrod();
bl_color* bl_color_palegreen();
bl_color* bl_color_paleturquoise();
bl_color* bl_color_palevioletred();
bl_color* bl_color_papayawhip();
bl_color* bl_color_peachpuff();
bl_color* bl_color_peru();
bl_color* bl_color_pink();
bl_color* bl_color_plum();
bl_color* bl_color_powderblue();
bl_color* bl_color_purple();
bl_color* bl_color_rebeccapurple();
bl_color* bl_color_red();
bl_color* bl_color_rosybrown();
bl_color* bl_color_royalblue();
bl_color* bl_color_saddlebrown();
bl_color* bl_color_salmon();
bl_color* bl_color_sandybrown();
bl_color* bl_color_seagreen();
bl_color* bl_color_seashell();
bl_color* bl_color_sienna();
bl_color* bl_color_silver();
bl_color* bl_color_skyblue();
bl_color* bl_color_slateblue();
bl_color* bl_color_slategray();
bl_color* bl_color_slategrey();
bl_color* bl_color_snow();
bl_color* bl_color_springgreen();
bl_color* bl_color_steelblue();
bl_color* bl_color_tan();
bl_color* bl_color_teal();
bl_color* bl_color_thistle();
bl_color* bl_color_tomato();
bl_color* bl_color_turquoise();
bl_color* bl_color_violet();
bl_color* bl_color_wheat();
bl_color* bl_color_white();
bl_color* bl_color_whitesmoke();
bl_color* bl_color_yellow();
bl_color* bl_color_yellowgreen();

#endif
